### ISSUE TITLE
Does not work with Elixir 3.0

### ISSUE THREAD

**Issue by drehimself** [EHLOVader/laravel-elixir-livereload#5]
I believe 3.0 has some API changes for extension creating: https://github.com/laravel/elixir/releases

Error when I run gulp:

module.js:340
    throw err;
          ^
Error: Cannot find module 'laravel-elixir/ingredients/commands/Utilities'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/path/to/project/node_modules/laravel-elixir-livereload/index.js:3:17)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

**Comment by EHLOVader** [comment]
Oh no! Nice find. 
I can look into this.

Also I should add elixir to this package too so hopefully it will warn you if you start upgrading further than I have been.

**Comment by LoveAndHappiness** [comment]
+1

**Comment by EHLOVader** [comment]
I didn't have a great test case for this. I haven't quite bumped my projects up to these new versions yet.

@drehimself  and @LoveAndHappiness could you take some time to try this fix out and let me know if it works as well as it had. Lots to improve upon but I think that can be the next step.

**Comment by drehimself** [comment]
@EHLOVader 

I updated my package.json file so laravel elixir is version 3.0.0 and this package is version 0.0.5. Ran a npm update and getting the following error upon trying to run gulp:

/path/to/project/gulpfile.js:16
    mix.livereload();
        ^
TypeError: Object #<Object> has no method 'livereload'
    at /path/to/project/gulpfile.js:16:9
    at Elixir (/path/to/project/node_modules/laravel-elixir/index.js:20:5)
    at Object.<anonymous> (path/to/project/gulpfile.js:14:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Liftoff.handleArguments (/usr/local/lib/node_modules/gulp/bin/gulp.js:108:3)

**Comment by EHLOVader** [comment]
Sorry I haven't had a chance to update the readme but I bumped versions to allow for backwards compatibility with L4.x/Elixir 2.x on the 0.x version of this extension...  Change the package.json to use ~1.1.0 for this from now on.

Originally thought I didn't publish, but it says 1.1.0 exists although it isn't listed on the NPM site. 

I hadn't pushed the tags, so perhaps that is the problem. @drehimself let me know here if you can get it working by explicitly setting the version in your package.json.

**Comment by EHLOVader** [comment]
Uhm, er perhaps I also forgot to publish. Check back in a few minutes.

**Comment by drehimself** [comment]
Thanks @EHLOVader it's working now.

Note I had to set laravel-elixir (^3.0.0) to be a dependency and not just a dev dependency in my package.json file. 

```
{
  "private": true,
  "devDependencies": {
    "gulp": "^3.8.8",
    "laravel-elixir-livereload": "1.1.0"
  },
  "dependencies": {
    "laravel-elixir": "^3.0.0"
  }
}
```

Laravel Elixir was previously just a dev dependency before. Looks like new versions of laravel are including it as a dependency, so it should be all good. Thanks again for updating your package, I can't see myself not using it!
